version: '3.7'

services:
  linking_wa:
    container_name: linking_wa
    build: .
    volumes:
      - './:/linking_wa'
      - '/linking_wa/node_modules'
    ports:
      - ${PORT}:${PORT}
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false
    stdin_open: true